<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Interviewer.Data\Interviewer.Data.csproj" />
    <ProjectReference Include="..\Interviewer.Infrastructure\Interviewer.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Prompts\Feedback.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Prompts\InterviewPlan.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
